<?php

namespace Database\Seeders;

use App\Models\ActualCountry;
use Illuminate\Database\Seeder;

class CoutriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            ['title_ru' => 'Россия', 'title_en' => 'Russia'],
            ['title_ru' => 'Украина', 'title_en' => 'Ukraine'],
            ['title_ru' => 'Беларусь', 'title_en' => 'Belarus'],
            ['title_ru' => 'Казахстан', 'title_en' => 'Kazakhstan'],
            ['title_ru' => 'Азербайджан', 'title_en' => 'Azerbaijan'],
            ['title_ru' => 'Армения', 'title_en' => 'Armenia'],
            ['title_ru' => 'Грузия', 'title_en' => 'Georgia'],
            ['title_ru' => 'Израиль', 'title_en' => 'Israel'],
            ['title_ru' => 'США', 'title_en' => 'USA'],
            ['title_ru' => 'Канада', 'title_en' => 'Canada'],
            ['title_ru' => 'Кыргызстан', 'title_en' => 'Kyrgyzstan'],
            ['title_ru' => 'Латвия', 'title_en' => 'Latvia'],
            ['title_ru' => 'Литва', 'title_en' => 'Lithuania'],
            ['title_ru' => 'Эстония', 'title_en' => 'Estonia'],
            ['title_ru' => 'Молдова', 'title_en' => 'Moldova'],
            ['title_ru' => 'Таджикистан', 'title_en' => 'Tajikistan'],
            ['title_ru' => 'Туркменистан', 'title_en' => 'Turkmenistan'],
            ['title_ru' => 'Узбекистан', 'title_en' => 'Uzbekistan'],
            ['title_ru' => 'Австралия', 'title_en' => 'Australia'],
            ['title_ru' => 'Австрия', 'title_en' => 'Austria'],
            ['title_ru' => 'Албания', 'title_en' => 'Albania'],
            ['title_ru' => 'Алжир', 'title_en' => 'Algeria'],
            ['title_ru' => 'Американское Самоа', 'title_en' => 'American Samoa'],
            ['title_ru' => 'Ангилья', 'title_en' => 'Anguilla'],
            ['title_ru' => 'Ангола', 'title_en' => 'Angola'],
            ['title_ru' => 'Андорра', 'title_en' => 'Andorra'],
            ['title_ru' => 'Антигуа и Барбуда', 'title_en' => 'Antigua and Barbuda'],
            ['title_ru' => 'Аргентина', 'title_en' => 'Argentina'],
            ['title_ru' => 'Аруба', 'title_en' => 'Aruba'],
            ['title_ru' => 'Афганистан', 'title_en' => 'Afghanistan'],
            ['title_ru' => 'Багамы', 'title_en' => 'Bahamas'],
            ['title_ru' => 'Бангладеш', 'title_en' => 'Bangladesh'],
            ['title_ru' => 'Барбадос', 'title_en' => 'Barbados'],
            ['title_ru' => 'Бахрейн', 'title_en' => 'Bahrain'],
            ['title_ru' => 'Белиз', 'title_en' => 'Belize'],
            ['title_ru' => 'Бельгия', 'title_en' => 'Belgium'],
            ['title_ru' => 'Бенин', 'title_en' => 'Benin'],
            ['title_ru' => 'Бермуды', 'title_en' => 'Bermuda'],
            ['title_ru' => 'Болгария', 'title_en' => 'Bulgaria'],
            ['title_ru' => 'Боливия', 'title_en' => 'Bolivia'],
            ['title_ru' => 'Босния и Герцеговина', 'title_en' => 'Bosnia and Herzegovina'],
            ['title_ru' => 'Ботсвана', 'title_en' => 'Botswana'],
            ['title_ru' => 'Бразилия', 'title_en' => 'Brazil'],
            ['title_ru' => 'Бруней-Даруссалам', 'title_en' => 'Brunei Darussalam'],
            ['title_ru' => 'Буркина-Фасо', 'title_en' => 'Burkina Faso'],
            ['title_ru' => 'Бурунди', 'title_en' => 'Burundi'],
            ['title_ru' => 'Бутан', 'title_en' => 'Bhutan'],
            ['title_ru' => 'Вануату', 'title_en' => 'Vanuatu'],
            ['title_ru' => 'Великобритания', 'title_en' => 'United Kingdom'],
            ['title_ru' => 'Венгрия', 'title_en' => 'Hungary'],
            ['title_ru' => 'Венесуэла', 'title_en' => 'Venezuela'],
            ['title_ru' => 'Виргинские острова, Британские', 'title_en' => 'British Virgin Islands'],
            ['title_ru' => 'Виргинские острова, США', 'title_en' => 'US Virgin Islands'],
            ['title_ru' => 'Восточный Тимор', 'title_en' => 'East Timor'],
            ['title_ru' => 'Вьетнам', 'title_en' => 'Vietnam'],
            ['title_ru' => 'Габон', 'title_en' => 'Gabon'],
            ['title_ru' => 'Гаити', 'title_en' => 'Haiti'],
            ['title_ru' => 'Гайана', 'title_en' => 'Guyana'],
            ['title_ru' => 'Гамбия', 'title_en' => 'Gambia'],
            ['title_ru' => 'Гана', 'title_en' => 'Ghana'],
            ['title_ru' => 'Гваделупа', 'title_en' => 'Guadeloupe'],
            ['title_ru' => 'Гватемала', 'title_en' => 'Guatemala'],
            ['title_ru' => 'Гвинея', 'title_en' => 'Guinea'],
            ['title_ru' => 'Гвинея-Бисау', 'title_en' => 'Guinea-Bissau'],
            ['title_ru' => 'Германия', 'title_en' => 'Germany'],
            ['title_ru' => 'Гибралтар', 'title_en' => 'Gibraltar'],
            ['title_ru' => 'Гондурас', 'title_en' => 'Honduras'],
            ['title_ru' => 'Гонконг', 'title_en' => 'Hong Kong'],
            ['title_ru' => 'Гренада', 'title_en' => 'Grenada'],
            ['title_ru' => 'Гренландия', 'title_en' => 'Greenland'],
            ['title_ru' => 'Греция', 'title_en' => 'Greece'],
            ['title_ru' => 'Гуам', 'title_en' => 'Guam'],
            ['title_ru' => 'Дания', 'title_en' => 'Denmark'],
            ['title_ru' => 'Доминика', 'title_en' => 'Dominica'],
            ['title_ru' => 'Доминиканская Республика', 'title_en' => 'Dominican Republic'],
            ['title_ru' => 'Египет', 'title_en' => 'Egypt'],
            ['title_ru' => 'Замбия', 'title_en' => 'Zambia'],
            ['title_ru' => 'Западная Сахара', 'title_en' => 'Western Sahara'],
            ['title_ru' => 'Зимбабве', 'title_en' => 'Zimbabwe'],
            ['title_ru' => 'Индия', 'title_en' => 'India'],
            ['title_ru' => 'Индонезия', 'title_en' => 'Indonesia'],
            ['title_ru' => 'Иордания', 'title_en' => 'Jordan'],
            ['title_ru' => 'Ирак', 'title_en' => 'Iraq'],
            ['title_ru' => 'Иран', 'title_en' => 'Iran'],
            ['title_ru' => 'Ирландия', 'title_en' => 'Ireland'],
            ['title_ru' => 'Исландия', 'title_en' => 'Iceland'],
            ['title_ru' => 'Испания', 'title_en' => 'Spain'],
            ['title_ru' => 'Италия', 'title_en' => 'Italy'],
            ['title_ru' => 'Йемен', 'title_en' => 'Yemen'],
            ['title_ru' => 'Кабо-Верде', 'title_en' => 'Cape Verde'],
            ['title_ru' => 'Камбоджа', 'title_en' => 'Cambodia'],
            ['title_ru' => 'Камерун', 'title_en' => 'Cameroon'],
            ['title_ru' => 'Катар', 'title_en' => 'Qatar'],
            ['title_ru' => 'Кения', 'title_en' => 'Kenya'],
            ['title_ru' => 'Кипр', 'title_en' => 'Cyprus'],
            ['title_ru' => 'Кирибати', 'title_en' => 'Kiribati'],
            ['title_ru' => 'Китай', 'title_en' => 'China'],
            ['title_ru' => 'Колумбия', 'title_en' => 'Colombia'],
            ['title_ru' => 'Коморы', 'title_en' => 'Comoros'],
            ['title_ru' => 'Конго', 'title_en' => 'Congo'],
            ['title_ru' => 'Конго, демократическая республика', 'title_en' => 'Congo, Democratic Republic'],
            ['title_ru' => 'Коста-Рика', 'title_en' => 'Costa Rica'],
            ['title_ru' => 'Кот д`Ивуар', 'title_en' => 'Côte d`Ivoire'],
            ['title_ru' => 'Куба', 'title_en' => 'Cuba'],
            ['title_ru' => 'Кувейт', 'title_en' => 'Kuwait'],
            ['title_ru' => 'Лаос', 'title_en' => 'Laos'],
            ['title_ru' => 'Лесото', 'title_en' => 'Lesotho'],
            ['title_ru' => 'Либерия', 'title_en' => 'Liberia'],
            ['title_ru' => 'Ливан', 'title_en' => 'Lebanon'],
            ['title_ru' => 'Ливия', 'title_en' => 'Libya'],
            ['title_ru' => 'Лихтенштейн', 'title_en' => 'Liechtenstein'],
            ['title_ru' => 'Люксембург', 'title_en' => 'Luxembourg'],
            ['title_ru' => 'Маврикий', 'title_en' => 'Mauritius'],
            ['title_ru' => 'Мавритания', 'title_en' => 'Mauritania'],
            ['title_ru' => 'Мадагаскар', 'title_en' => 'Madagascar'],
            ['title_ru' => 'Макао', 'title_en' => 'Macau'],
            ['title_ru' => 'Македония', 'title_en' => 'Macedonia'],
            ['title_ru' => 'Малави', 'title_en' => 'Malawi'],
            ['title_ru' => 'Малайзия', 'title_en' => 'Malaysia'],
            ['title_ru' => 'Мали', 'title_en' => 'Mali'],
            ['title_ru' => 'Мальдивы', 'title_en' => 'Maldives'],
            ['title_ru' => 'Мальта', 'title_en' => 'Malta'],
            ['title_ru' => 'Марокко', 'title_en' => 'Morocco'],
            ['title_ru' => 'Мартиника', 'title_en' => 'Martinique'],
            ['title_ru' => 'Маршалловы Острова', 'title_en' => 'Marshall Islands'],
            ['title_ru' => 'Мексика', 'title_en' => 'Mexico'],
            ['title_ru' => 'Микронезия, федеративные штаты', 'title_en' => 'Micronesia'],
            ['title_ru' => 'Мозамбик', 'title_en' => 'Mozambique'],
            ['title_ru' => 'Монако', 'title_en' => 'Monaco'],
            ['title_ru' => 'Монголия', 'title_en' => 'Mongolia'],
            ['title_ru' => 'Монтсеррат', 'title_en' => 'Montserrat'],
            ['title_ru' => 'Мьянма', 'title_en' => 'Myanmar'],
            ['title_ru' => 'Намибия', 'title_en' => 'Namibia'],
            ['title_ru' => 'Науру', 'title_en' => 'Nauru'],
            ['title_ru' => 'Непал', 'title_en' => 'Nepal'],
            ['title_ru' => 'Нигер', 'title_en' => 'Niger'],
            ['title_ru' => 'Нигерия', 'title_en' => 'Nigeria'],
            ['title_ru' => 'Кюрасао', 'title_en' => 'Curaçao'],
            ['title_ru' => 'Нидерланды', 'title_en' => 'Netherlands'],
            ['title_ru' => 'Никарагуа', 'title_en' => 'Nicaragua'],
            ['title_ru' => 'Ниуэ', 'title_en' => 'Niue'],
            ['title_ru' => 'Новая Зеландия', 'title_en' => 'New Zealand'],
            ['title_ru' => 'Новая Каледония', 'title_en' => 'New Caledonia'],
            ['title_ru' => 'Норвегия', 'title_en' => 'Norway'],
            ['title_ru' => 'Объединенные Арабские Эмираты', 'title_en' => 'United Arab Emirates'],
            ['title_ru' => 'Оман', 'title_en' => 'Oman'],
            ['title_ru' => 'Остров Мэн', 'title_en' => 'Isle of Man'],
            ['title_ru' => 'Остров Норфолк', 'title_en' => 'Norfolk Island'],
            ['title_ru' => 'Острова Кайман', 'title_en' => 'Cayman Islands'],
            ['title_ru' => 'Острова Кука', 'title_en' => 'Cook Islands'],
            ['title_ru' => 'Острова Теркс и Кайкос', 'title_en' => 'Turks and Caicos Islands'],
            ['title_ru' => 'Пакистан', 'title_en' => 'Pakistan'],
            ['title_ru' => 'Палау', 'title_en' => 'Palau'],
            ['title_ru' => 'Палестинская автономия', 'title_en' => 'Palestine'],
            ['title_ru' => 'Панама', 'title_en' => 'Panama'],
            ['title_ru' => 'Папуа - Новая Гвинея', 'title_en' => 'Papua New Guinea'],
            ['title_ru' => 'Парагвай', 'title_en' => 'Paraguay'],
            ['title_ru' => 'Перу', 'title_en' => 'Peru'],
            ['title_ru' => 'Питкерн', 'title_en' => 'Pitcairn Islands'],
            ['title_ru' => 'Польша', 'title_en' => 'Poland'],
            ['title_ru' => 'Португалия', 'title_en' => 'Portugal'],
            ['title_ru' => 'Пуэрто-Рико', 'title_en' => 'Puerto Rico'],
            ['title_ru' => 'Реюньон', 'title_en' => 'Réunion'],
            ['title_ru' => 'Руанда', 'title_en' => 'Rwanda'],
            ['title_ru' => 'Румыния', 'title_en' => 'Romania'],
            ['title_ru' => 'Сальвадор', 'title_en' => 'El Salvador'],
            ['title_ru' => 'Самоа', 'title_en' => 'Samoa'],
            ['title_ru' => 'Сан-Марино', 'title_en' => 'San Marino'],
            ['title_ru' => 'Сан-Томе и Принсипи', 'title_en' => 'São Tomé and Príncipe'],
            ['title_ru' => 'Саудовская Аравия', 'title_en' => 'Saudi Arabia'],
            ['title_ru' => 'Свазиленд', 'title_en' => 'Swaziland'],
            ['title_ru' => 'Святая Елена', 'title_en' => 'Saint Helena'],
            ['title_ru' => 'Северная Корея', 'title_en' => 'North Korea'],
            ['title_ru' => 'Северные Марианские острова', 'title_en' => 'Northern Mariana Islands'],
            ['title_ru' => 'Сейшелы', 'title_en' => 'Seychelles'],
            ['title_ru' => 'Сенегал', 'title_en' => 'Senegal'],
            ['title_ru' => 'Сент-Винсент', 'title_en' => 'Saint Vincent and the Grenadines'],
            ['title_ru' => 'Сент-Китс и Невис', 'title_en' => 'Saint Kitts and Nevis'],
            ['title_ru' => 'Сент-Люсия', 'title_en' => 'Saint Lucia'],
            ['title_ru' => 'Сент-Пьер и Микелон', 'title_en' => 'Saint Pierre and Miquelon'],
            ['title_ru' => 'Сербия', 'title_en' => 'Serbia'],
            ['title_ru' => 'Сингапур', 'title_en' => 'Singapore'],
            ['title_ru' => 'Сирийская Арабская Республика', 'title_en' => 'Syria'],
            ['title_ru' => 'Словакия', 'title_en' => 'Slovakia'],
            ['title_ru' => 'Словения', 'title_en' => 'Slovenia'],
            ['title_ru' => 'Соломоновы Острова', 'title_en' => 'Solomon Islands'],
            ['title_ru' => 'Сомали', 'title_en' => 'Somalia'],
            ['title_ru' => 'Судан', 'title_en' => 'Sudan'],
            ['title_ru' => 'Суринам', 'title_en' => 'Suriname'],
            ['title_ru' => 'Сьерра-Леоне', 'title_en' => 'Sierra Leone'],
            ['title_ru' => 'Таиланд', 'title_en' => 'Thailand'],
            ['title_ru' => 'Тайвань', 'title_en' => 'Taiwan'],
            ['title_ru' => 'Танзания', 'title_en' => 'Tanzania'],
            ['title_ru' => 'Того', 'title_en' => 'Togo'],
            ['title_ru' => 'Токелау', 'title_en' => 'Tokelau'],
            ['title_ru' => 'Тонга', 'title_en' => 'Tonga'],
            ['title_ru' => 'Тринидад и Тобаго', 'title_en' => 'Trinidad and Tobago'],
            ['title_ru' => 'Тувалу', 'title_en' => 'Tuvalu'],
            ['title_ru' => 'Тунис', 'title_en' => 'Tunisia'],
            ['title_ru' => 'Турция', 'title_en' => 'Turkey'],
            ['title_ru' => 'Уганда', 'title_en' => 'Uganda'],
            ['title_ru' => 'Уоллис и Футуна', 'title_en' => 'Wallis and Futuna'],
            ['title_ru' => 'Уругвай', 'title_en' => 'Uruguay'],
            ['title_ru' => 'Фарерские острова', 'title_en' => 'Faroe Islands'],
            ['title_ru' => 'Фиджи', 'title_en' => 'Fiji'],
            ['title_ru' => 'Филиппины', 'title_en' => 'Philippines'],
            ['title_ru' => 'Финляндия', 'title_en' => 'Finland'],
            ['title_ru' => 'Фолклендские острова', 'title_en' => 'Falkland Islands'],
            ['title_ru' => 'Франция', 'title_en' => 'France'],
            ['title_ru' => 'Французская Гвиана', 'title_en' => 'French Guiana'],
            ['title_ru' => 'Французская Полинезия', 'title_en' => 'French Polynesia'],
            ['title_ru' => 'Хорватия', 'title_en' => 'Croatia'],
            ['title_ru' => 'Центрально-Африканская Республика', 'title_en' => 'Central African Republic'],
            ['title_ru' => 'Чад', 'title_en' => 'Chad'],
            ['title_ru' => 'Чехия', 'title_en' => 'Czech Republic'],
            ['title_ru' => 'Чили', 'title_en' => 'Chile'],
            ['title_ru' => 'Швейцария', 'title_en' => 'Switzerland'],
            ['title_ru' => 'Швеция', 'title_en' => 'Sweden'],
            ['title_ru' => 'Шпицберген и Ян Майен', 'title_en' => 'Svalbard and Jan Mayen'],
            ['title_ru' => 'Шри-Ланка', 'title_en' => 'Sri Lanka'],
            ['title_ru' => 'Эквадор', 'title_en' => 'Ecuador'],
            ['title_ru' => 'Экваториальная Гвинея', 'title_en' => 'Equatorial Guinea'],
            ['title_ru' => 'Эритрея', 'title_en' => 'Eritrea'],
            ['title_ru' => 'Эфиопия', 'title_en' => 'Ethiopia'],
            ['title_ru' => 'Южная Корея', 'title_en' => 'South Korea'],
            ['title_ru' => 'Южно-Африканская Республика', 'title_en' => 'South Africa'],
            ['title_ru' => 'Ямайка', 'title_en' => 'Jamaica'],
            ['title_ru' => 'Япония', 'title_en' => 'Japan'],
            ['title_ru' => 'Черногория', 'title_en' => 'Montenegro'],
            ['title_ru' => 'Джибути', 'title_en' => 'Djibouti'],
            ['title_ru' => 'Южный Судан', 'title_en' => 'South Sudan'],
            ['title_ru' => 'Ватикан', 'title_en' => 'Vatican'],
            ['title_ru' => 'Синт-Мартен', 'title_en' => 'Sint Maarten'],
            ['title_ru' => 'Бонайре, Синт-Эстатиус и Саба', 'title_en' => 'Bonaire, Sint Eustatius and Saba'],
            ['title_ru' => 'Англия', 'title_en' => 'England'],
            ['title_ru' => 'Косово', 'title_en' => 'Kosovo'],
            ['title_ru' => 'Шотландия', 'title_en' => 'Scotland'],
            ['title_ru' => 'Уэльс', 'title_en' => 'Wales'],
        ];

        foreach ($countries as $country) {
            ActualCountry::updateOrCreate(
                ['title_en' => $country['title_en']],
                ['title_ru' => $country['title_ru']],
            );
        }
    }
}
